### ISSUE TITLE
[Enhancement] Add nodeSelector support to helm chart 

### ISSUE THREAD

**Issue by randallice** [SolaceProducts/pubsubplus-kubernetes-helm-quickstart#111]
We have started testing using the helm chart to deploy into our kubernetes test environment and would like to see if support for kubernetes nodeSelector to be added to the solaceStatefulSet.yaml template.  We have added support to ours but it would be better to see the support added to the project than to maintain a fork internally.

This is an example of what we added to the template to allow us to use nodeSelector keys in our yaml passed to heml:
```yaml
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}
```
That allows us to pass where we ant to run in the yaml or at the command line to helm along with other settings that we override:

example yaml file:
```yaml
solace:
  redundancy: false
  image.repository: <our registry>
  image.tag: 9.3.1.8
  usernameAdminPassword: <out password>
  nameOverride: <our name>

nodeSelector:
   electron.side : "b-side"
```
